$mod = SUPER
quiet = true

# --- LAUNCHER ---
$menu = wofi --show drun


# MONITOR
monitor=,preferred,auto,1

# --- Screenshots ---
bind = , Print, exec, grim - | wl-copy
bind = $mod, Print, exec, grim -g "$(slurp)" - | wl-copy


# VARIABLES
$mod = SUPER
$terminal = kitty
$browser = firefox
$menu = wofi --show drun

# --- ASCII Color Palette ---
$background = rgba(12,13,17,1.0)
$foreground = rgba(200,200,200,1.0)

$accent = rgba(138,21,67,1.0)        # blood red
$accent_dark = rgba(92,14,45,1.0)    # border red
$selection = rgba(27,29,36,1.0)


# AUTOSTART
#exec-once = swaync
exec-once = swww-daemon
exec-once = dunst
exec-once = nm-applet
exec-once = waybar
#exec-once = command -v waypaper >/dev/null && waypaper --restore || true
exec-once = wl-paste --watch cliphist store
exec-once = ~/.local/bin/battery-check.sh


# KEYBINDS
bind = $mod, Return, exec, $terminal
bind = $mod, D, exec, $menu
bind = $mod, F, fullscreen
bind = $mod, Q, killactive
bind = $mod, M, exit
bind = SUPER, Space, exec, $menu
bind = SUPER, A, exec, ~/.config/rofi/scripts/launcher_t1
bind = SUPER, V, exec, system-control
bind = SUPER, D, exec, ~/.config/rofi/scripts/launcher_t1
bind = SUPER, SPACE, exec, ~/.config/rofi/scripts/launcher_t1
bind = SUPER, B, exec, kitty -e bluetuith
bind = SUPER, L, exec, hyprlock
bind = SUPER, P, exec, ~/.config/rofi/scripts/powermenu.sh
bind = SUPER, N, exec, swaync-client -t
bind = $mod, E, exec, kitty -e yazi
bind = $mod SHIFT, R, exec, ~/.local/bin/record.sh
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9


# Volume controls (NO terminal, NO mixer)
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5 && swaync-client -R
bind = , XF86AudioLowerVolume, exec, pamixer -d 5 && swaync-client -R
bind = , XF86AudioMute, exec, pamixer -t && swaync-client -R


# FLOATING
bind = $mod, T, togglefloating

decoration {
    rounding = 0

    blur {
       enabled = false
    }

    shadow {
   enabled = true
        range = 6
        render_power = 2
        color = rgba(138,21,67,60)
    }

    active_opacity = 1.0
    inactive_opacity = 1.0
}


# global border
border_size = 2
border_color = $accent

general {
    gaps_in = 5
    gaps_out = 12
    layout = dwindle
border_size = 2

    col.active_border = $accent
    col.inactive_border = rgba(42,42,42,1.0)

}

animations {
    enabled = yes
    animation = windows,1,2,linear
    animation = border,1,2,linear
    animation = fade,1,2,linear
    animation = workspaces,1,2,linear
}


windowrule = opacity 0.82, match:class ^(Thunar)$
windowrule = opacity 0.82, match:class ^(soundcloud|Soundcloud)$

# MOVE WINDOW
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
#layerrule = blur, waybar, 1
#layerrule = ignorezero, waybar
#layerrule = xray 0, waybar, 0

# ===============================
# Bottom-right popups (Windows-style)
# ===============================


env = XCURSOR_THEME,Bibata-Original-Ice
env = XCURSOR_SIZE,24
